### PR TITLE
Assign PR step created

### LINKED ISSUE #204: Task-Auto assign Pull Request
## Task Summary
- Pull Request should have assignee as to linked/ closing issues.

## Acceptance Criteria
- [ ] Whenever Pull Request it must get assigned
- [ ] For existing Pull Request assignee must be from closing reference issues.

## Subtasks
- NA
  
## Related Issues
- NA

## Additional Notes
- NA

### PR DESCRIPTION
**Pull request by ajayg2808**
## Description
- Assign pull request with all available events (not handled yet - `pull_request: opened`) 
- Assign Pull Request if not assigned
- If already assigned and some assignee are missing add comment on pull request.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Project Configuration
- [x] Repository Configuration
- [ ] Documentation update - Code guide/ docs (_like, javadoc or api_)
- [ ] Other (please describe):

## Screenshots / GIFs / Media (if applicable)
- NA

## How Has This Been Tested?/ Test Plan
- Change development branch to default.

## Checklist:
- [x] My code follows the project’s [coding guidelines](./../../docs/guidelines/coding-guides/). 
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code where necessary.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] I have added tests that verify the functionality of the code (if applicable).
- [x] All new and existing tests pass.

## How to use/ enable
- Default branch should have updated github action changes (project.yml)

## Additional Notes
- NA

## Closing issues
closes #204

### CODE REVIEW

**Comment by serv-cat** [comment]
This pull request does not reference any closing issues.</br>Link reference closing issues to proceed further with this PR.

**Comment by serv-cat** [comment]
Below issue owners are not assigned to this pull request:<br>Asignees of issue #204

**Comment by serv-cat** [comment]
Below issue owners are not assigned to this pull request:<br>Asignees of issue #204<br>@0

**Comment by serv-cat** [comment]
Below issue owners are not assigned to this pull request:<br>Asignees of issue #204<br>- @serv-cat

**Comment by serv-cat** [comment]
Below issue owners are not assigned to this pull request:

**Comment by serv-cat** [comment]
Below issue owners are not assigned to this pull request:

**Review by ajayg2808 — COMMENTED** [review]
Done

**Pull request merged**
